name: 'wp'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql/
    networks:
      - inception-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - '7000:9000'
    env_file:
      - .env
    volumes:
      - website:/var/www/html/
    networks:
      - inception-network
    restart: always


  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html/
      # - ./logs/nginx:/var/log/nginx/
    networks:
      - inception-network
    restart: always

  uptime-kuma:
    container_name: uptime
    build: ./requirements/bonus/uptime
    ports:
      - "3001:3001"
    volumes:
      - uptime:/app/data
    networks:
      - inception-network
    restart: unless-stopped

networks:
  inception-network:
    name: inception-network
    driver: bridge

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /home/edwin/42/42_inception/srcs/data/database
      o: bind
  website:
    driver: local
    driver_opts:
      type: none
      device: /home/edwin/42/42_inception/srcs/data/website
      o: bind
  uptime:
    driver: local
    driver_opts:
      type: none
      device: /home/edwin/42/42_inception/srcs/data/uptime
      o: bind